pipeline {
    agent any

    tools {
        maven "maven3"
    }

    environment {
        GIT_CREDENTIALS = 'GitHub'
        IMAGE_NAME = 'rupesh1997/one-tier-app'
        DOCKERHUB_CREDENTIALS = 'DockerHub'
        GIT_URL = 'https://github.com/rupesh-hub/one-tier-app-jenkins-k8s.git'
        SONAR_HOME = tool "sonar"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: env.GIT_CREDENTIALS, url: env.GIT_URL
            }
        }

        stage('Build') {
            steps {
                sh '''
                    cd backend
                    mvn clean package -DskipTests
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    cd backend
                    mvn clean test
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("sonar") {
                    sh '''
                        $SONAR_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=one-tier-app \
                        -Dsonar.projectKey=one-tier-app \
                        -Dsonar.exclusions=**/*.java
                    '''
                }
            }
        }

        stage('Prepare Docker Image') {
            steps {
                sh '''
                    cd backend
                    docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} -f ../docker/backend/Dockerfile .
                '''
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: env.DOCKERHUB_CREDENTIALS, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push ${IMAGE_NAME}:${BUILD_NUMBER}
                    '''
                }
            }
        }

//         stage('Run with Docker Compose') {
//             steps {
//                 sh 'docker-compose down || true'  // Stop existing containers if running
//                 sh 'docker-compose pull'          // Ensure the latest image is pulled
//                 sh 'docker-compose up -d'         // Run the app in detached mode
//             }
//         }

        stage('Update Deployment File') {
            environment {
                        GIT_REPO_NAME = "one-tier-app-jenkins-k8s"
                        GIT_USER_NAME = "rupesh77"
            }

            steps {
                withCredentials([string(credentialsId: env.GITHUB_TOKEN, variable: 'GITHUB_TOKEN')]) {
                    sh '''
                        git config user.email "dulalrupesh77@gmail.com"
                        git config user.name "Rupesh Dulal"
                        BUILD_NUMBER=${BUILD_NUMBER}
                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" deployment/backend-deployment.yml
                        git add deployment/backend-deployment.yml
                        git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                    '''
                }
            }
        }
    }

    // Post-build actions
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs for details.'
        }
    }
}
