kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    app: backend
  namespace: one-tier-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rupesh1997/one-tier-app:36
        ports:
        - containerPort: 8181
