kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
  namespace: one-tier-app

spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181